### ISSUE TITLE
Image in article body

### ISSUE THREAD

**Issue by pr0xity** [gathering/tgno-backend#19]
We need a way to show a image using the id of the image

Images from the article body looks like this 
`<embed embedtype=\"image\" format=\"fullwidth\" id=\"7\" alt=\"TG-promo-6\"/>`

**Comment by pr0xity** [comment]
Also need to have a look at the main image output in the json from [https://dev.tg.no/api/v2/news/12/](https://dev.tg.no/api/v2/news/12/)
Currently gives
```json
    "main_image": {
        "url": "/media/images/20220113211909-302b6da0-me.2e16d0ba.fill-100x100.jpg",
        "full_url": "https://dev.tg.no/media/images/20220113211909-302b6da0-me.2e16d0ba.fill-100x100.jpg",
        "width": 100,
        "height": 100,
        "alt": "Gamer over shoulder picture"
    }
``` 

But we want a bigger image not 100x100...

**Comment by mfyll** [comment]
Issue closed, this is already working 👍 💯 🥇
